/**
 * Official DOCX generation.
 *
 *   master bytes (read-only)  →  verify identity  →  splice document.xml  →  generated bytes
 *
 * The master is never written to. 39 of the 40 package entries are carried through as their
 * original compressed bytes; only `word/document.xml` is rebuilt.
 */

import { readZip, writeZip, entryText, sha256Hex } from '../ooxml/zip.js';
import { indexDocument, assertPristineShape } from '../ooxml/docxpatch.js';
import { applyEdits, scan, descendants, textOf, child } from '../ooxml/xmlscan.js';
import { resolveEdits } from './resolve.js';

export class TemplateMismatchError extends Error {
  constructor(detail) {
    super('Unsupported or updated IDFL application template detected. Field mapping must be reviewed.');
    this.name = 'TemplateMismatchError';
    this.detail = detail;
  }
}

export class OverflowError extends Error {
  constructor(overflow) {
    super('申請内容が公式様式の行数を超えています。');
    this.name = 'OverflowError';
    this.overflow = overflow;
  }
}

/**
 * Verify the loaded bytes really are the supported master before touching anything.
 * @throws {TemplateMismatchError}
 */
export async function verifyTemplate(masterBytes, mapping) {
  const sha256 = await sha256Hex(masterBytes);
  if (sha256 !== mapping.master.sha256) {
    throw new TemplateMismatchError({
      reason: 'sha256-mismatch', expected: mapping.master.sha256, actual: sha256,
    });
  }
  return { sha256 };
}

/**
 * Build the populated document.
 *
 * @param {Uint8Array} masterBytes  bytes of the official master (never mutated)
 * @param {object} mapping          templates/<version>/mapping.json
 * @param {object} data             ApplicationData
 * @param {{allowOverflow?:boolean}} [options]
 * @returns {Promise<{bytes:Uint8Array, filename:string, report:object}>}
 */
export async function generateDocx(masterBytes, mapping, data, options = {}) {
  const { sha256 } = await verifyTemplate(masterBytes, mapping);

  const { entries } = readZip(masterBytes);
  const target = entries.find((e) => e.name === mapping.master.part);
  if (!target) throw new TemplateMismatchError({ reason: 'missing-part', part: mapping.master.part });

  const xml = await entryText(target);
  const doc = indexDocument(xml);
  // the master must match the shape these population rules were written against
  assertPristineShape(doc);

  if (doc.controls.length !== mapping.master.controlCount) {
    throw new TemplateMismatchError({
      reason: 'control-count-mismatch',
      expected: mapping.master.controlCount, actual: doc.controls.length,
    });
  }
  if (doc.ballots.length !== mapping.master.ballotCount) {
    throw new TemplateMismatchError({
      reason: 'ballot-count-mismatch',
      expected: mapping.master.ballotCount, actual: doc.ballots.length,
    });
  }

  const { edits, applied, overflow, warnings } = resolveEdits(doc, mapping, data);

  // Refuse rather than silently truncate — a partially-populated official application
  // that looks complete is worse than no document at all.
  if (overflow.length && !options.allowOverflow) throw new OverflowError(overflow);

  const patched = applyEdits(xml, edits);

  /* ---- post-conditions, before anything is packaged ---- */
  const check = indexDocument(patched);   // re-scans; throws if the XML is malformed
  if (check.controls.length !== doc.controls.length) {
    throw new Error(`control count changed during population: ${doc.controls.length} → ${check.controls.length}`);
  }
  if (check.ballots.length + countTicked(patched) !== doc.ballots.length) {
    // ballots that were ticked are no longer "☐", so the two must sum back to the original count
    throw new Error('ballot accounting mismatch after population');
  }
  verifyStructure(xml, patched);

  const outBytes = await writeZip(entries.map((e) =>
    e.name === mapping.master.part
      ? { ...e, replacement: new TextEncoder().encode(patched) }
      : e));

  return {
    bytes: outBytes,
    filename: buildFilename(data),
    report: {
      templateVersion: mapping.templateVersion,
      masterSha256: sha256,
      controlsInMaster: doc.controls.length,
      editsApplied: edits.length,
      fieldsPopulated: applied.length,
      applied, overflow, warnings,
      partsRewritten: [mapping.master.part],
      partsCarriedThrough: entries.length - 1,
    },
  };
}

function countTicked(xmlText) {
  // ballots we ticked became ☒ in a run outside any sdt; count them the same way indexDocument does
  const { root } = scan(xmlText);
  return descendants(root, 'w:t').filter((t) => {
    for (let n = t.parent; n; n = n.parent) if (n.name === 'w:sdt') return false;
    return textOf(xmlText, t) === '☒';
  }).length;
}

/** Cheap structural invariants: the population must not add or remove document furniture. */
function verifyStructure(before, after) {
  const a = scan(before).root;
  const b = scan(after).root;
  for (const tag of ['w:tbl', 'w:tr', 'w:tc', 'w:p', 'w:sectPr', 'w:drawing', 'w:pict', 'w:bookmarkStart']) {
    const na = descendants(a, tag).length;
    const nb = descendants(b, tag).length;
    if (na !== nb) throw new Error(`structure changed: <${tag}> ${na} → ${nb}`);
  }
}

/** `IDFL_GOTS-TE_Application_<company>_<yyyymmdd>.docx`, filesystem-safe. */
export function buildFilename(data, now = new Date()) {
  const raw = data?.applicant?.companyNameEnglish?.trim()
    || data?.applicant?.companyName?.trim()
    || 'Application';
  const safe = raw
    .replace(/[\\/:*?"<>|]/g, '')       // characters Windows forbids
    .replace(/[\u0000-\u001F]/g, '')
    .replace(/\s+/g, '-')
    .replace(/[.\-]+$/g, '')
    .slice(0, 60) || 'Application';
  const stamp = [
    now.getFullYear(),
    String(now.getMonth() + 1).padStart(2, '0'),
    String(now.getDate()).padStart(2, '0'),
  ].join('');
  return `IDFL_GOTS-TE_Application_${safe}_${stamp}.docx`;
}
