#!/usr/bin/env python3
"""
Extract every Word Content Control from an IDFL master template.

READ-ONLY. This script never writes to the .docx it is given.

Usage:
    python tools/gots-te-qa/extract-controls.py "<path to master.docx>" [-o docs/gots-te-application/_generated]

Outputs (into -o):
    control-inventory.tsv    one row per control, human-diffable
    control-inventory.json   same data, for the field-map build step
    template-identity.json   doc number / ref / DCN / sha256 / control counts

Why this exists
---------------
The master addresses its 342 controls by `w:id` only: 21 of them carry a w:tag/w:alias and
those 21 names are duplicated, so names cannot be keys. `w:id` values are regenerated by Word
whenever a control is copied, so a new template release can silently renumber everything.

Run this against each new IDFL release, diff the TSV against the previous one, and update the
field map before the new template goes live. Only stdlib is required.
"""
import argparse, collections, hashlib, json, os, re, sys, zipfile
import xml.etree.ElementTree as ET

W = "{http://schemas.openxmlformats.org/wordprocessingml/2006/main}"
W14 = "{http://schemas.microsoft.com/office/word/2010/wordml}"
BALLOT = "☐☑☒"


def text_of(el, skip_controls=False):
    if el is None:
        return ""
    if not skip_controls:
        return "".join(t.text or "" for t in el.iter(W + "t")).strip()
    buf = []

    def walk(e):
        for ch in e:
            if ch.tag == W + "sdt":
                continue          # exclude answers, keep only the printed label
            if ch.tag == W + "t":
                buf.append(ch.text or "")
            else:
                walk(ch)

    walk(el)
    return "".join(buf).strip()


def row_cells(tr):
    """Ordered cells of a row, unwrapping content controls that wrap whole cells.

    191 of the 342 controls sit at `w:tr > w:sdt > w:sdtContent > w:tc`, so a naive
    findall('w:tc') silently loses more than half the form.
    """
    out = []
    for node in tr:
        if node.tag == W + "tc":
            out.append(node)
        elif node.tag == W + "sdt":
            cont = node.find(W + "sdtContent")
            if cont is not None:
                out.extend(sub for sub in cont if sub.tag == W + "tc")
    return out


def control_kind(sdt):
    pr = sdt.find(W + "sdtPr")
    if pr is None:
        return "UNKNOWN", []
    kind, items = "TEXT", []
    for child in pr:
        if child.tag == W + "comboBox":
            kind = "COMBO"
            items = [li.get(W + "displayText") or li.get(W + "value") or ""
                     for li in child.findall(W + "listItem")]
        elif child.tag == W + "dropDownList":
            kind = "DROP"
            items = [li.get(W + "displayText") or li.get(W + "value") or ""
                     for li in child.findall(W + "listItem")]
        elif child.tag == W14 + "checkbox":
            kind = "CHK"
        elif child.tag == W + "date":
            kind = "DATE"
        elif child.tag == W + "text":
            kind = "TEXT"
        elif child.tag == W + "picture":
            kind = "PIC"
    return kind, items


def extract(docx_path):
    with zipfile.ZipFile(docx_path) as z:
        doc = z.read("word/document.xml")
        header = z.read("word/header1.xml") if "word/header1.xml" in z.namelist() else b"<x/>"
        settings = z.read("word/settings.xml")

    root = ET.fromstring(doc)
    parent = {c: p for p in root.iter() for c in p}

    def ancestor(el, tag):
        n = parent.get(el)
        while n is not None:
            if n.tag == W + tag:
                return n
            n = parent.get(n)
        return None

    tables = list(root.iter(W + "tbl"))
    tbl_no = {t: i + 1 for i, t in enumerate(tables)}

    # Section = last paragraph whose text STARTS with セクション<digits>.
    # Anchoring matters: the body contains cross-references such as
    # 「…セクション9-12を参照…」 which a substring match reads as a heading.
    sec_re = re.compile(r"^セクション\s*([0-9０-９]+)")
    zen = str.maketrans("０１２３４５６７８９", "0123456789")

    ordered, current = [], "0"
    for el in root.iter():
        if el.tag == W + "p":
            t = text_of(el)
            m = sec_re.match(t)
            if m and len(t) < 200:
                current = m.group(1).translate(zen)
        elif el.tag == W + "sdt":
            ordered.append((el, current))

    rows = []
    for i, (sdt, sec) in enumerate(ordered, 1):
        pr = sdt.find(W + "sdtPr")

        def prop(name):
            e = pr.find(W + name) if pr is not None else None
            return e.get(W + "val") if e is not None else None

        kind, items = control_kind(sdt)
        tr, tbl, tc = ancestor(sdt, "tr"), ancestor(sdt, "tbl"), ancestor(sdt, "tc")
        row_no = col_no = None
        row_label = col_header = cell_text = ""

        if tr is not None and tbl is not None:
            trs = [r for r in tbl if r.tag == W + "tr"]
            row_no = trs.index(tr) + 1
            cs = row_cells(tr)
            for ci, c in enumerate(cs, 1):
                if c is tc or any(x is sdt for x in c.iter()):
                    col_no = ci
                    break
            if cs:
                row_label = text_of(cs[0], skip_controls=True)[:70]
            if col_no and trs:
                hdr = row_cells(trs[0])
                if len(hdr) >= col_no:
                    col_header = text_of(hdr[col_no - 1], skip_controls=True)[:50]
            if tc is not None:
                cell_text = text_of(tc, skip_controls=True)[:70]
        else:
            cell_text = text_of(ancestor(sdt, "p"), skip_controls=True)[:70]

        rows.append({
            "n": i, "section": sec, "kind": kind,
            "id": prop("id"), "tag": prop("tag"), "alias": prop("alias"),
            "table": tbl_no.get(tbl), "row": row_no, "col": col_no,
            "rowLabel": row_label, "cellText": cell_text, "colHeader": col_header,
            "items": items,
            "placeholder": text_of(sdt.find(W + "sdtContent"))[:40],
        })

    # ballot glyphs living outside any control cannot be filled as controls
    def inside_control(el):
        n = parent.get(el)
        while n is not None:
            if n.tag == W + "sdt":
                return True
            n = parent.get(n)
        return False

    plain_ballots = collections.Counter()
    for t in root.iter(W + "t"):
        if any(ch in BALLOT for ch in (t.text or "")) and not inside_control(t):
            owner = ancestor(t, "tc")
            if owner is None:
                owner = ancestor(t, "p")
            plain_ballots[text_of(owner)[:80]] += 1

    hroot = ET.fromstring(header)
    header_lines = [ln for ln in
                    ("".join(x.text or "" for x in p.iter(W + "t")).strip()
                     for p in hroot.iter(W + "p")) if ln]

    sroot = ET.fromstring(settings)
    prot = sroot.find(W + "documentProtection")

    identity = {
        "file": os.path.basename(docx_path),
        "sha256": hashlib.sha256(open(docx_path, "rb").read()).hexdigest(),
        "headerLines": header_lines,
        "documentProtection": dict(prot.attrib) if prot is not None else None,
        "controlTotal": len(rows),
        "controlsByKind": dict(collections.Counter(r["kind"] for r in rows)),
        "controlsBySection": dict(sorted(collections.Counter(r["section"] for r in rows).items(),
                                         key=lambda kv: int(kv[0]))),
        "namedControls": sum(1 for r in rows if r["tag"] or r["alias"]),
        "duplicateNames": {n: c for n, c in
                           collections.Counter(r["tag"] for r in rows if r["tag"]).items() if c > 1},
        "uniqueIds": len({r["id"] for r in rows}) == len(rows),
        "plainTextBallotBoxes": dict(plain_ballots),
    }
    return rows, identity


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("docx")
    ap.add_argument("-o", "--out", default="docs/gots-te-application/_generated")
    a = ap.parse_args()

    if not os.path.isfile(a.docx):
        sys.exit(f"not found: {a.docx}")
    os.makedirs(a.out, exist_ok=True)

    rows, identity = extract(a.docx)

    cols = ["n", "section", "kind", "id", "table", "row", "col",
            "rowLabel", "cellText", "colHeader", "items", "placeholder"]
    with open(os.path.join(a.out, "control-inventory.tsv"), "w", encoding="utf-8") as f:
        f.write("\t".join(cols) + "\n")
        for r in rows:
            f.write("\t".join(
                ("/".join(r[c]) if c == "items" else str(r[c])).replace("\t", " ")
                for c in cols) + "\n")
    for name, data in (("control-inventory.json", rows), ("template-identity.json", identity)):
        with open(os.path.join(a.out, name), "w", encoding="utf-8") as f:
            json.dump(data, f, ensure_ascii=False, indent=1)

    print(f"{identity['controlTotal']} controls  {identity['controlsByKind']}")
    print(f"by section: {identity['controlsBySection']}")
    print(f"named: {identity['namedControls']}  duplicate names: {identity['duplicateNames']}")
    print(f"unique w:id: {identity['uniqueIds']}")
    print(f"plain-text ballot boxes (NOT fillable): {sum(identity['plainTextBallotBoxes'].values())}")
    print(f"sha256: {identity['sha256']}")
    print(f"-> {a.out}")


if __name__ == "__main__":
    main()
